data = importdata("input.txt", " ");
levels = diff(data, 1, 2);
safeLevels = ...
( ...
    all(levels > 0 | isnan(levels), 2) | ...
    all(levels < 0 | isnan(levels), 2) ...
) & ...
all(abs(levels) <= 3 | isnan(levels), 2);
fprintf("Number of Safe Levels: %d\n", sum(safeLevels));